# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.0.2

executors:
  ci-node:
    docker:
      - image: mcr.microsoft.com/playwright:v1.22.0-focal

jobs:
  cache-deps:
    parameters:
      key:
        type: string
    executor: ci-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - << parameters.key >>
      - run: npm install -g npm@latest
      - run: npm install
      - save_cache:
          paths:
            - "~/project/node_modules"
            - "/usr/local/lib/node_modules"
          key: << parameters.key >>

  test-w-playwright:
    executor: ci-node
    steps:
      - checkout
      - restore_cache:
           keys:
             - npm-svelte-{{ arch }}-{{ checksum "package-lock.json" }}
      - run: npm run test

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test_w_playwright: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      # - node/test:
      #     # This is the node version to use for the `cimg/node` tag
      #     # Relevant tags can be found on the CircleCI Developer Hub
      #     # https://circleci.com/developer/images/image/cimg/node
      #     version: '16.10'
      #     # If you are using yarn, change the line below from "npm" to "yarn"
      #     pkg-manager: npm
      - cache-deps:
          key: npm-svelte-{{ arch }}-{{ checksum "package-lock.json" }}
      - test-w-playwright:
          requires:
            - "cache-deps"
