# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

executors:
  ci-node:
    docker:
      - image: mcr.microsoft.com/playwright:v1.22.0-focal

jobs:
  cache-deps:
    parameters:
      key:
        type: string
    executor: ci-node
    # machine:
    # image: mcr.microsoft.com/playwright:v1.22.0-focal
    # docker_layer_caching: true <- This Feature is available for paid plan
    steps:
      - checkout
      - restore_cache:
          keys:
            - << parameters.key >>
      - run: npm install -g npm@latest
      - run: npm install -g pnpm
      - run: pnpm install
      - save_cache:
          paths:
            - 'node_modules'
            - '~/project/node_modules'
            - '/usr/local/lib/node_modules'
          key: << parameters.key >>

  test-w-playwright:
    executor: ci-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - pnpm-svelte-{{ arch }}-{{ checksum "pnpm-lock.yaml" }}
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run test

  build:
    working_directory: /app
    docker:
      - image: docker:20-git
    steps:
      - checkout
      - setup_remote_docker
        # docker_layer_caching: false;
      - run: ls -ls

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test_w_playwright: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - cache-deps:
          key: pnpm-svelte-{{ arch }}-{{ checksum "pnpm-lock.yaml" }}
      - test-w-playwright:
          requires:
            - 'cache-deps'
